apiVersion: v1
kind: Deployment
metadata:
  name: myweb-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      env: production
    matchExpression:
      - {key: app, operator: IN, values: [myweb-dep]}
  template:
    metadata:
      name: myweb-pod
      labels:
        env: production
        app: myweb-dep
    spec:
      containers:
      - name: myweb-con
        image: vimal13/apache-webserver-php:v2